// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD_Gg67xFrF8RJFMBQM8rWJPvmtS-a-4E',
    appId: '1:528958367333:web:5b9e3b7e39f983d11f488c',
    messagingSenderId: '528958367333',
    projectId: 'flutter-rankmarket',
    authDomain: 'flutter-rankmarket.firebaseapp.com',
    storageBucket: 'flutter-rankmarket.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZthLjD_QkXffDZiOJp9C6X5Ll2R3l1yo',
    appId: '1:528958367333:android:0fbcdb2dad8674371f488c',
    messagingSenderId: '528958367333',
    projectId: 'flutter-rankmarket',
    storageBucket: 'flutter-rankmarket.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIN-u1gHAYsmXPcGMjTFZrb_7oVOIiBps',
    appId: '1:528958367333:ios:3806a49697134abd1f488c',
    messagingSenderId: '528958367333',
    projectId: 'flutter-rankmarket',
    storageBucket: 'flutter-rankmarket.appspot.com',
    iosBundleId: 'com.example.rankmarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIN-u1gHAYsmXPcGMjTFZrb_7oVOIiBps',
    appId: '1:528958367333:ios:805f1c37da55ed5b1f488c',
    messagingSenderId: '528958367333',
    projectId: 'flutter-rankmarket',
    storageBucket: 'flutter-rankmarket.appspot.com',
    iosBundleId: 'com.example.rankmarket.RunnerTests',
  );
}
